src/pydrex/deformation_mechanism.py
src/pydrex/fabric.py
src/pydrex/stiffness.py
src/pydrex/tensors.py

Add modules for handling:
- deformation mechanisms
- crystalline fabrics
- experimental stiffnesses
- tensor operations

refactor: Add refactored helper modules

---

data/2d_mesh_test.py
data/pydrex.ini
src/pydrex/exceptions.py
src/pydrex/io.py
src/pydrex/vtk_helpers.py

Adds modules to handle VTK and parameter input.
More tests should be added in time, but for now some simple mock files are added in data/.
To see how the parameter parsing works, run `parse_params("data/pydrex.ini")`.
Configuration file format is INI, because that's what Python's configparser understands.

refactor: Add input handlers

---

src/pydrex/core.py
src/pydrex/run.py

Adds the module `run` which contains the main entry point `main`.
The entry point handles command line arguments and also parallelisation (soon).
Output is stored in a diagnostics dict and saved to a NPZ file.

refactor: Add entry point module and debug logging

---

src/pydrex/run.py

Maybe this can be configurable in future.

feat: Filter unwieldy numba log messages

---

src/pydrex/core.py

Don't raise a possibly negative number to a power

fix: Fix strain energy calculation for enstatite

---

src/pydrex/run.py

First step of bringing multiprocessing back to the refactored code.

feat: Re-enable shared-memory multiprocessing

---

src/pydrex/core.py

For now these nodes will run for t* = 1 (dimensionless) i.e. t = max. strain rate.
Soon I should introduce the option to integrate for a preconfigured time
instead of waiting for the pathline to exit the domain.

fix: Handle zero-velocity nodes (bypass pathline calculation)

---

src/pydrex/deformation_mechanism.py
src/pydrex/fabric.py

Breaking change, the example won't run anymore until the new API arrives.
There were also some errors in the translated RK4 scheme which will be fixed soon.

refactor: Prepare deformation mechanim.py and fabric.py for API overhaul

---

.github/workflows/ci.yml
setup.cfg
src/pydrex/minerals.py
tests/conftest.py

- Replace ad-hoc RK4 with scipy version
- clean up pytest fixtures
~~- add test file for aggregate tests~~
- add CI file for test automation
All tests should pass in ~10s currently. ~~The mineral aggregate test is a work-in-progress (it doesn't validate the results enough yet). I think there is still an issue with grain nucleation or something, because it looks like the grain size distribution is changed very drastically, very quicly. Some mockup plots of the olivine a-axis distribution also don't quite seem to match what they should right now.~~

Add CI file and migrate to scipy ivp

---

tests/test_core.py

Quick fix for the assertion, have done the same for the other tests.

test: Make assertion for random init case more robust

---

tests/test_simple_shear_2d.py

Fixes flaky tests discovered in #44 .

Fix flaky tests

---

tests/test_simple_shear_2d.py

test: Fix flaky tolerance value

---

tests/test_simple_shear_2d.py

Fixes flaky tolerance values discovered during work on #50.

test: Fix flaky tolerance values

---

.github/workflows/ci.yml

Avoid deprecation warning from CI

MAINT: Update action version

---

tools/h5part_reader.py

h5part -> NPZ, a bit slow to convert but gives a 60x smaller file, use something like the following to animate pole figures along a pathline:
```
import numpy as np
from scipy import linalg as la
from matplotlib import pyplot as plt
from matplotlib.animation import FuncAnimation
from pydrex import diagnostics as _diagnostics
from pydrex import minerals as _minerals
def set_polefig_axis(ax, ref_axes="xz"):
ax.set_axis_off()
ax.set_xlim((-1.1, 1.1))
ax.set_ylim((-1.1, 1.1))
ax.set_aspect("equal")
_circle_points = np.linspace(0, np.pi * 2, 100)
ax.plot(np.cos(_circle_points), np.sin(_circle_points), linewidth=1, color="k")
ax.axhline(0, color="k")
ax.text(1.05, 0.5, ref_axes[0], verticalalignment="center", transform=ax.transAxes)
ax.axvline(0, color="k")
ax.text(
0.5, 1.05, ref_axes[1], …
```

feat: Add script to read fluidity h5part files

---

src/pydrex/diagnostics.py
src/pydrex/minerals.py
src/pydrex/stats.py
src/pydrex/visualisation.py
tests/test_corner_flow_2d.py

Remove 3/4 cornerflow tests which are pretty redundant, and add some code for pole figures. Add some asserts for the remaining cornerflow test. A few other fixes here and there as well, commits can probably be squashed because it got a bit messy.

Fix 2d corner flow

---

src/pydrex/diagnostics.py
src/pydrex/stats.py
src/pydrex/visualisation.py
tests/test_corner_flow_2d.py
tests/test_diagnostics.py
tests/test_simple_shear_2d.py

Fixes the M-index method, adds some girdle symmetry tests and diagnostics. Adds method to calculate average stiffness tensor (which was in the old PyDRex).

Fixes and additions to stats and diagnostics

---

data/thirdparty/Kaminski2002_ISAtime.scsv
data/thirdparty/Kaminski2004_AaxisDynamicShear.scsv
src/pydrex/io.py

Quick fix for silly errors in data file I/O.

fix: Fix SCSV file headers and reader

---

src/pydrex/minerals.py
tests/test_core.py

- Make documentation of CRSS more precise
- Add missing enum docstrings
- Promote comments to docstrings in core tests
- Make print statements into logging calls

More documentation fixes

---

data/thirdparty/Kaminski2002_ISAtime.scsv
data/thirdparty/Kaminski2004_AaxisDynamicShear.scsv
src/pydrex/io.py
tests/test_scsv.py

Ran into some untested cases earlier today.

fix: Fix SCSV schema validation and add validation test

---

src/pydrex/diagnostics.py

Closes #97
Not sure about the stretch (strain) measure exactly, there seem to be various derived strain measures used in different papers but my understanding is that they are all computed from the principal stretch ratios, see e.g.
https://classes.engineering.wustl.edu/2009/spring/mase5513/abaqus/docs/v6.6/books/stm/default.htm?startat=ch01s04ath05.html

feat: Add FSE diagnostic

---

src/pydrex/legacy.py
tests/test_simple_shear_2d.py

Adds a method that replicates the original RK solver, almost as a drop-in replacement for Mineral.update_orientations except a few extra arguments are required in the call signature.

feat: Add legacy K&R2004 Runge Kutta solver

---

src/pydrex/stats.py
tests/test_diagnostics.py

And add a CI test to prevent it happening again.

fix: Fix orientation resampling

---

pyproject.toml
src/pydrex/io.py
tests/test_scsv.py

fix: Fix SCSV I/O to prevent writing unreadable data.

---

src/pydrex/utils.py

docs: Fix docstring for strain increment calculation

---

src/pydrex/utils.py
src/pydrex/visualisation.py
tests/conftest.py
tests/test_core.py
tests/test_corner_flow_2d.py
tests/test_simple_shear_2d.py
tests/test_vortex_2d.py
tools/h5part_reader.py

Some final tweaks to visualisation functions.

Visualisation

---

examples/fluidity/advection2d/Makefile
examples/fluidity/advection2d/advection2d.flml

A few cleaning chores I missed in #174.

style: Clean unused variables from Fluidity advection2d example

---

src/pydrex/diagnostics.py
src/pydrex/mesh.py
src/pydrex/minerals.py
src/pydrex/tensors.py

Some small final additions to doctests to help catch regressions and demonstrate usage.

Finalise doctests for current methods

---

pyproject.toml
src/pydrex/io.py

The extractor can take a while so it is useful to know how much progress has been made on the command line.

style: Add tqdm progress bar to h5part extractor

---

src/pydrex/utils.py
src/pydrex/visualisation.py

A few small changes that helped to get the final figures in the paper

fix: Fix handling of kwargs in important visualisation functions

---

CHANGELOG.md
README.md
pyproject.toml
src/pydrex/__init__.py
tests/test_doctests.py

Could add release automation or do it later
Closes #185

Cut manual alpha release

---

.pre-commit-config.yaml
pyproject.toml
src/pydrex/__init__.py
src/pydrex/axes.py
src/pydrex/cli.py
src/pydrex/core.py
src/pydrex/diagnostics.py
src/pydrex/distributed.py
src/pydrex/exceptions.py
src/pydrex/geometry.py
src/pydrex/io.py
src/pydrex/logger.py
src/pydrex/minerals.py
src/pydrex/pathlines.py
src/pydrex/stats.py
src/pydrex/tensors.py
src/pydrex/utils.py
src/pydrex/velocity.py
src/pydrex/visualisation.py
tests/README.md
tests/conftest.py
tests/test_config.py
tests/test_core.py
tests/test_doctests.py
tests/test_geometry.py
tests/test_scsv.py
tests/test_tensors.py
tests/test_vortex_2d.py
tools/venv_install.sh

Some initial prep before the variable visc tests. After this we should be able to restore the [pre-commit ci bot](https://github.com/apps/pre-commit-ci) if we want.
Closes #196 as per the discussion there.

General clean
