src/pydrex/interpolations.py, src/pydrex/vtk_helpers.py
Adds some functions to organise interpolator callbacks.
This was previously handled in `main`. At the moment the option to use
matplotlib interpolation is handled in command line args.
It could make sense to move that into the configuration file later.
=> refactor: Add interpolation callbacks and helpers.

src/pydrex/core.py, src/pydrex/io.py
Adds routines for:
- solving the DRex equations for steady state flow (`solve`)
- pathline calculation (`get_pathline`)
- iterative strain calculation (`update_strain`)
- iterative orientation calculation (`update_orientations`)
- rotation rate calculation (`get_rotation_rates`)
- strain energy residual calculation (`get_strain_energy_residuals`)
which relate to the previous methods as follows:
- `solve` implements most of `DRex` and the pathline loop from `strain`.
- `get_pathline` is mostly a copy of `pathline`.
- `update_strain` implements RK4 for the finite strain ellipsoid (`strain`)
- `update_orientations` implements RK4 for orientations and volume bins (`strain`)
- `get_rotation_rates` and `get_strain_energy_residuals`
are called by `update_orientations` at each step (`deriv`) …
=> refactor: Add core PyDRex routines

src/pydrex/core.py
It's one of the things that could make the `n_iterations` get unwieldy.
=> feat: Add grid_steps to logging info

src/pydrex/run.py
It was happening too early, before the grid mask is updated
=> fix: Fix calculation of number of completed nodes

src/pydrex/core.py
[Recommended by numpy][1] and generally ~5% faster from my simple testing.
[1]: https://numpy.org/doc/stable/reference/generated/numpy.dot.html?highlight=matrix%20multiplication
=> perf: Use matmul instead of numpy `dot`

examples/shearbox/run.sh, examples/shearbox/src/shearbox_500.ini, examples/shearbox/src/shearbox_500_particles.flml, examples/shearbox/src/shearbox_gmsh.py, examples/shearbox/src/shearbox_pydrex.py, examples/shearbox/src/shearbox_single.ini, examples/shearbox/src/shearbox_single_particle.flml, pyproject.toml, setup.cfg, setup.py
Currently CPO is calculated for the whole domain,
probably needs a way to mask nodes that we are not interested in?
=> feat: Add draft of shearbox example

src/pydrex/core.py, src/pydrex/minerals.py, tests/test_core.py
In all of the literature, "rotation rate" is not the derivative da/dt,
but actually the ω tensor, where a = k exp(- ∫ω dt).
In Fraters 2021 these are distinct tensors,
whereas at the moment we just calculate da/dt in one go.
It may be necessary to split this up for some advection methods.
=> style: Change naming convention for orientation derivatives

src/pydrex/core.py
Should be multiplied by the previous grain size arrray,
see eq. 12 in Kaminski 2004 and eq. 10 & 11 in Fraters 2021.
(This was correct in PyDRex.py, I didn't copy it across correctly).
=> fix: Fix grain size derivatie calculation

src/pydrex/minerals.py, tests/test_core.py
Renaming some stuff, a new test at the end. Random initialisation for single grains is doing the right thing according to the (less strict) eigenvalue metric from Vollmer 1990.
Pushed to the wrong remote, will delete this branch after.
=> Add more grain tests

tests/test_core.py
I will do this, however, to make sure the largest eigenvalue is "significantly" different. For now just `0.1`, I'm still looking for a good way to choose that value.
=> test: Increase minimum difference of largest eigenvalue.

tests/test_core.py
Removes the incorrect test for single grain rotation rates.
Single grains with random starting orientation are not a valid test.
Furthermore, I misunderstood the Vollmer eigenvalue diagnostics,
and olivine A-type should approach Girdle symmetry for the
[100] orientation, not Point symmetry, e.g. [Boneh et al., 2015]
[Boneh et al., 2015]: https://doi.org/10.1002/2015GC005964
=> Remove incorrect single grain test

.github/workflows/ci.yml, src/pydrex/diagnostics.py, tests/test_diagnostics.py
Add methods to calculate bingham average and M-index (texture strength).
Will be used in other tests so if these fail other test results are invalid.
~~Not sure why the bingham averages for b- and c-axes are not orthogonal,
but that isn't important until we are looking at e.g. B-type olivine.~~ Fixed
I have also snuck the proper Vollmer diagnostics back in here, but they need more tests.
=> feat: Add bingham average and M-index diagnostics

src/pydrex/diagnostics.py, tests/test_diagnostics.py
The calculation can take a long time with loops.
For 1000 grains there are 499500 matrix multiplications.
Vectorized, it is fast enough to use in tests (at least for one polycrystal).
Numba could be necessary for larger tests, we'll see.
Also added module docs and a few small extras.
=> Texture diagnostics

src/pydrex/minerals.py, src/pydrex/visualisation.py, tests/conftest.py, tests/test_simple_shear_2d.py
Adds a 2D simple shear test. Optionally save the output figure with:
pytest --outdir="out/"
where "out/" is the name of an existing directory (can be "." for cwd).
Have been tweaking the tolerances for a while, hopefully not too flaky... M* is grain boundary mobility and the red dashed line is the analytical result for a single grain if it started at 45°.
=> Simple shear test

src/pydrex/visualisation.py, tests/README.md, tests/conftest.py, tests/test_simple_shear_2d.py
Adds a 2d simple shear test which varies the grain boundary sliding parameter.
This uses parameters from Kaminski 2004. Grain boundary sliding acts as an
upper bound on texture strength and a lower bound on CPO alignment.
The initial contition is set up for shear along a different axis,
but slip on the same slip system as the GBM test from https://github.com/Patol75/PyDRex/pull/38
(this tests that the model is working regardless of the orientation of the 2D shear).
=> GBS test and small test fixes

src/pydrex/minerals.py
Makes no sense to ignore it just becuase the file doesn't exist.
=> fix: Always use append mode when postfix is given

data/specs/spec.scsv, setup.cfg, src/pydrex/io.py, src/pydrex/logger.py, src/pydrex/minerals.py, src/pydrex/visualisation.py, src/pydrex/vtk_helpers.py, tests/README.md, tests/conftest.py, tests/test_scsv.py
Full SCSV I/O and tests. These files will not only be used for third party datasets but also to save pathlines from standalone runs, to complement the NPZ files which only store CPO information.
=> Finalise SCSV format

src/pydrex/diagnostics.py, tests/test_corner_flow_2d.py
Progress towards #88 (reduces peak mem usage by a bit over half). I think this approach is better than implementing an iterator, which causes a significant (3x minimum) CPU time increase even with mutliprocessing. The other method can be added later if needed.
For 20,000 grains, the routines now need to allocate just under 300GB. This is feasible on normalsr NCI queues (memory-rich HPC queues), and more grains than that doesn't make sense even for testing.
For 10,000 grains, which is the absolute maximum of what I would consider "normal use", we need to allocate just under 75GB. This is not too bad, maybe even some smaller clusters can do it.
I should probably document the memory requirements somewhere eventually. But a bonus of preallocating the array is that any simulations will now …
=> Use quaternions in postprocessing

src/pydrex/logger.py
For fluidity models I need to write to the log file in append mode, because I call `enable_logfile` at each simulation step.
=> feat: Expose mode setting of logfile

src/pydrex/exceptions.py, src/pydrex/io.py
While trying to read an old SCSV pathline file, I found that the generic error message by itself is not very helpful. This adds log messages when the SCSV schema of a file/dataset cannot be validated which describe the reason for failure.
=> feat: Add error logging to SCSV validation

src/pydrex/core.py, src/pydrex/logger.py, src/pydrex/minerals.py, src/pydrex/mock.py, src/pydrex/stats.py, src/pydrex/visualisation.py, tests/conftest.py, tests/test_core.py, tests/test_corner_flow_2d.py, tests/test_scsv.py, tests/test_simple_shear_2d.py, tools/h5part_reader.py
Adds some enstatite tests to catch a Numba typing issue when multiphase minerals were used, and refactors some symbols to avoid the crash.
This refactoring avoids the need for explicit numba type signatures which led to more numba errors for other tests.
=> Add core OPX tests

pyproject.toml, src/pydrex/cli.py, src/pydrex/visualisation.py
Makes it easy to run `pydrex-polefigure` from the command line to plot pole figures of a serialized pydrex output (.npz file). The thing has it's own `--help` and all that stuff.
Also fixes a typo bug that appeared `visualisation.polefigures`.
=> feat: Add command line polefigure plotting tool.

tools/h5part_reader.py, tools/venv_install.sh
=> Fix h5part reader and add venv install script

src/pydrex/minerals.py, tests/test_simple_shear_2d.py
Closes #89
Uses a default bandwidth of 12000 (lband = uband = 6000), and exposes the options to the user via Mineral() and Mineral.update_orientations().
=> fix: Implement banded Jacobian for n_grains > 4632

tests/test_simple_shear_2d.py
When the multiprocessing module is used, the difference in perf_counter() values is actually total time for all processes including sleep time, which is essentially just a more pessimistic version of process_time() that gives the total active CPU time.
Also small typo fix in line 464.
=> test: Remove perf_counter() time because it's not really walltime

src/pydrex/visualisation.py, tests/test_simple_shear_2d.py
This reworks the ensemble test to be a parametrized set of ensemble tests for varying GBM, GBS and nucleation values. Plots show the effect of GBM for the chosen pair of GBS and nucleation, because GBM (M*) is the most important/least constrained of the three.
Ensemble tests don't compare to experiments nor the fortran, because these are targeted at testing the effects of the pydrex parameters specifically. I'll add a test back in vs the fortran and experiments soon.
Also here I only compute the angle diagnostic, because symmetry/strength diagnostics are expensive and don't add a lot here (I'll use separate more focused tests to compare to Boneh2015 or something).
5000 grains is good enough for steady simple shear, see #131 . I split it up using pytest parametrisation because that allows …
=> test: Rework 2D simple shear ensemble test

src/pydrex/diagnostics.py
=> fix: Fix default number of CPUs for parallel M-index calculation

src/pydrex/utils.py, src/pydrex/visualisation.py, tests/test_core.py, tests/test_simple_shear_2d.py
Adds a couple of core tests for rotation rate and grain growth with initial grain orientations distributed on a circle (either in the plane of deformation or in the shear plane). The output figures offer some more clarity on what is happening with recrystallisation. For the first of these tests it was possible to derive analytical results for comparison. Unlike the ensemble 2D tests, these are fast enough to run in CI (a few seconds) because only the initial instantaneous rotation rate and grain growth values are checked.
This is the figure for the in-plane test. Both subparallel and suborthogonal grains want to grow in size, as well as a sharp peak at +/- 45 degrees from these directions. The rest of the grains have negative growth values which means they will shrink. The bottom figure …
=> Core rotation rate and grain growth tests

src/pydrex/data/drexF90/olA_D1E4_dt50_X0_L5.scsv, tests/test_corner_flow_2d.py, tests/test_simple_shear_2d.py
Also removed the redundant GBS ensemble (GBS example is covered by the big `test_dvdx_ensemble` example). Removed basic n_grains test which didn't have asserts, to be replaced with a more complete convergence test.
=> test: Add GBM sanity check CI tests and mark cornerflow as slow

src/pydrex/core.py, src/pydrex/minerals.py
- fixed incorrect indentation for raising an error on unknown enstatite fabric input
- removed redundant enstatite slip rate multiplication factor (it always evaluates to 1 anyway becuase the single active slip system of enstatite always has τ∗=1 by definition; this is also the case for the Fortran code actually)
- put enstatite/olivine volume fraction switch inside the LSODA right hand side solve, to make the code read in a more intuitive execution order and not use inherited magic variables from the enclosing scope
=> fix: Minor fixes to core.py and minerals.py

src/pydrex/diagnostics.py, src/pydrex/geometry.py, src/pydrex/velocity.py, src/pydrex/visualisation.py, tests/test_corner_flow_2d.py, tests/test_simple_shear_2d.py, tests/test_vortex_2d.py
Also fixes a bug with `misorientation_indices` which caused mixed up M-index outputs and apparent non-reproducible behaviour.
I have removed the old assert statements on this test for now as they don't really test much, also this test is too long for CI anyway and not very tractable as an ensemble test either, so it is mainly qualitative, but at least shows if the M-index is working.
=> test: Add reworked 2D cornerflow example

tests/test_vortex_2d.py
Fixes the 2D cell plots to look like before #152
=> fix: Fix velocity arrows and tick labels in 2D cell plot

.github/workflows/ci.yml, README.md, pyproject.toml, src/pydrex/diagnostics.py, src/pydrex/io.py, src/pydrex/logger.py, src/pydrex/stats.py, src/pydrex/utils.py, src/pydrex/visualisation.py, tests/conftest.py, tests/test_core.py, tests/test_corner_flow_2d.py, tests/test_scsv.py, tests/test_simple_shear_2d.py, tests/test_vortex_2d.py, tools/venv_install.sh
- Use PDF for all figures
- Remove redundant old plotting functions
- Use a safe wrapper to get a default number of CPUs for Linux, Mac or Windows
- Make the `venv_install.sh` script support `PYTHON_BINARY` for using custom paths to local Python installations (e.g. 3.11 on cosgrove)
=> Fixes to test figure output and multi-platform support

src/pydrex/core.py, src/pydrex/utils.py, src/pydrex/visualisation.py, tests/test_simple_shear_2d.py
Produces the final version of the GBM vs fortran test as per overleaf manuscript.
The legend was overprinting traces at a font size of 18 so I moved it outside the axes.
=> feat: Make redraw_legend more flexible; finalise GBM test figure legend

src/pydrex/diagnostics.py, src/pydrex/io.py, src/pydrex/visualisation.py, tests/conftest.py, tests/test_simple_shear_2d.py
Adds one more simple shear test showing all the relevant (A-type ~~and D-type~~) data from the compilation of Skemer & Hansen, 2016, Tectonophysics. I mention these data in the manuscript and he helpfully provided me with the raw data file so it doesn't hurt to include this.
This may help to choose which value of M* to recommend as default: the Kaminski & Ribe and Fraters & Billen choice of 125 or the Boneh et al. and Faccenda & VanderBeek choice of 10.
=> 2d shear calibration test

src/pydrex/cli.py, src/pydrex/mock.py, src/pydrex/visualisation.py, tests/test_corner_flow_2d.py, tests/test_simple_shear_3d.py
Test inspired by Fraters 2021 Fig 5 but now with the correct angle projections. No figure by default because it's an ensemble, instead the data for both plots is saved for each switch time, plotting just requires loading the saved data and giving it to `visualisation.alignment`.
Other stuff included here:
- small fix to the pole figure plotting function for correct use of the optional `strains.scsv` files in some tests
- fix typo in number of grains in `mock.params_Fraters2021` (500 -> 5000)
=> test: Add 3D shear test (Fraters 2021)

src/pydrex/__init__.py, src/pydrex/cli.py, src/pydrex/diagnostics.py, src/pydrex/io.py, src/pydrex/logger.py, tests/conftest.py, tests/test_diagnostics.py
- adjust `src/pydrex/__init__.py` to populate top-level namespace (i.e. what symbols you get from simply doing `import pydrex`)
- `LOGGER_CONSOLE` -> `CONSOLE_LOGGER` to match our documentation
- `pydrex.diagnostics.symmetry` -> `pydrex.diagnostics.symmetry_pgr` to avoid future namespace conflicts
- delete useless `meshio.read` wrapper, just use `meshio.read` directly
=> refactor: Populate pydrex namespace and adjust some symbol names

src/pydrex/stats.py
This fixes an occasional IndexError that occurs during resampling, if np.cumsum(fractions_ascending) < rng.random(), which results in np.searchsorted() returning an index outside the size of the new arrays.
=> fix: Fix IndexError resulting from cumsum(fractions)[-1] != 1

tests/test_simple_shear_3d.py
Save average M-index for the Fraters2021 test, to give a better idea of what is going on with the texture strength.
=> test: Add CPO strength output for Fraters2021 test

src/pydrex/diagnostics.py, src/pydrex/minerals.py, src/pydrex/pathlines.py, src/pydrex/utils.py, src/pydrex/velocity.py, tests/test_corner_flow_2d.py, tests/test_simple_shear_2d.py, tests/test_vortex_2d.py
Adds a 2D simple shear test that includes advection along a pathline.
Also a test to check that `utils.strain_increment` is working and some minor documentation fixes.
=> Add 2D advection test

examples/fluidity/advection2d/Makefile, src/pydrex/cli.py, src/pydrex/mesh.py
Adds simple resolution gradient functionality to the mesh generator.
CLI example:
```
pydrex-mesh -k="rectangle" -a xy 1,1 -rN:1e-2,S:1e-3 out.msh                                  [bg:1]
```
API example:
```
>>> rect = rectangle(
...     "test_rect",
...     ("x", "z"),
...     center=(0, 0),
...     width=1,
...     height=1,
...     resolution={"north-west": 1e-3, "south-east": 1e-2},
...     _write_file=False
... )
>>> rect.point_constraints[1][-1]
0.01
>>> rect.point_constraints[3][-1]
0.001
>>> rect.point_constraints[0][-1] == rect.point_constraints[2][-1]
True
>>> rect.point_constraints[0][-1]
0.0055
```
This will allow for setting a higher resolution near the ridge/corner in the initial mesh which we feed to Fluidity.
=> feat: Add resolution gradient support in the mesh generator

examples/fluidity/README.md, examples/fluidity/advection2d/advection2d.flml, examples/fluidity/advection2d/advection2d.py, examples/fluidity/corner2d/Makefile, examples/fluidity/corner2d/corner2d.flml, examples/fluidity/corner2d/corner2d.py, src/pydrex/geometry.py, src/pydrex/minerals.py, src/pydrex/pathlines.py, src/pydrex/stats.py, src/pydrex/velocity.py, src/pydrex/visualisation.py, tests/README.md, tests/test_corner_flow_2d.py, tests/test_simple_shear_2d.py, tests/test_simple_shear_3d.py, tests/test_vortex_2d.py, tools/find_45_seeds.py
Includes the `float32` patch to make M-index calculations less heavy.
=> Add Fluidity cornerflow 2d example

.github/workflows/ci.yml, pyproject.toml, src/pydrex/io.py, tests/conftest.py, tests/test_scsv.py
Python > 3.10 can cause issues with Fluidity which I keep running into. Angus is on the case, but in the meantime, it wasn't much work to add support for Python 3.10 (assuming the CI behaves).
=> dev: Add support for Python 3.10 and test against 3.10-3.12

examples/fluidity/corner2d/corner2d.flml
We need to spawn some particles to stop the h5part data from being cut off when particles start to exit the domain. Within the particle spawning shim, it's necessary to return an empty list (and not None) if particles should not be spawned at that particular time.
=> fix: Fix fl-corner2d example

README.md, src/pydrex/diagnostics.py, tools/venv_install.sh
Nothing new here, just fixing some documentation. README now suggests installing the PyPi release, elasticity tensor decomposition properly references symmetry of the medium instead of "minerals" (which reads as if it were single-crystal symmetry) and the venv install script sets up a proper dev environment with some ignore rules. First of many PRs in the next while, but I'm cutting them up to be manageable.
=> Documentation fixes/improvements

pyproject.toml, src/pydrex/__init__.py, src/pydrex/core.py, src/pydrex/geometry.py, src/pydrex/io.py, src/pydrex/logger.py, src/pydrex/mesh.py, src/pydrex/minerals.py, src/pydrex/tensors.py, src/pydrex/utils.py, src/pydrex/velocity.py, src/pydrex/visualisation.py, tests/README.md, tests/conftest.py, tests/test_core.py, tests/test_corner_flow_2d.py, tests/test_doctests.py, tests/test_scsv.py, tests/test_simple_shear_2d.py, tests/test_simple_shear_3d.py, tests/test_vortex_2d.py, tools/perf_compare.sh, tools/simple_shear_2d.py
Some more rebased commits. Adds texture evolution (or lack thereof) for diffusion creep (with tests) and yielding. There are a few commented alternative ways to do diffusion creep, I'd like to leave them in as comments for now in case I come back to it.
Other things:
- simpler way to generate text file listing final particle locations
- peridotite solidus from Herzberg 2000 (with easy way to add other fits)
- get second order tensor invariants (e.g. for strain tensor)
- remove duplicated `PERMUTATION_SYMBOL` in `tensors` (it's in `core`)
- some test/visualisation improvements, requiring `dill` to allow "pickling" lexical closures
- the diffusion creep test (in `test_vortex2d`) relies on the above
- optional mypy depencency (and lsp plugin) for dev environment
=> Add diffusion and yielding

CHANGELOG.md, src/pydrex/__init__.py, src/pydrex/logger.py, src/pydrex/minerals.py, tests/test_doctests.py
On line 638 of `minerals.py`.
Closes https://github.com/seismic-anisotropy/PyDRex/issues/198. Also rearranges definitions so that globals are above classes are above functions. This allows for mypy type hints of the multiphase function args.
This fix was brought to you by mypy static type linting.
=> Add multiphase texture update API

.pre-commit-config.yaml
And then we hit the big green button [over here](https://github.com/apps/pre-commit-ci) again.
=> dev: Bump versions of pre-commit tools

tools/venv_install.sh
Running the pre-commit hooks locally eliminates the need to rebase onto changes that the pre-commit-ci bot commits. This makes the PR process smoother for contributors. But in case someone can't install or build the pre-commit binary, this warning is not fatal to the venv installer.
=> dev: Add missing pre-commit executable warning to the venv installer

src/pydrex/io.py, src/pydrex/mesh.py, tests/conftest.py, tests/test_doctests.py, tests/test_simple_shear_2d.py, tests/test_simple_shear_3d.py
These changes should fix the current syntax check failure from CI following pre-commit integration.
=> Ensure pre-commit hooks pass

CHANGELOG.md, Makefile, README.md, pyproject.toml, src/pydrex/__init__.py, src/pydrex/core.py, src/pydrex/io.py, src/pydrex/logger.py, src/pydrex/mesh.py, src/pydrex/minerals.py, src/pydrex/mock.py, tests/README.md, tests/conftest.py, tests/test_doctests.py, tests/test_scsv.py, tests/test_simple_shear_3d.py
- Some changes to logging, sending some symbols to `pydrex.io` instead
- Changes to `pydrex.logger` documentation, recommending use of `logging.getLogger("pydrex")` for users (which will not mess with their numpy printoptions)
- more robust pytest live logging plugin and setup, with early errors if the couple of problematic pytest command line options are discovered (and collapsing `-v` and `log_cli=true` into the same behaviour)
- type validation during construction of some dataclasses
- `live_docs` make target, allows browsing up to date documentation while editing
- closes #211 
No `QueueHandler` for multiprocessing just yet.
=> Fix logging/pytest setup and make mock objects subclasses of `DefaultParams`

src/pydrex/minerals.py
Loosening the `atol` tolerance for the main LSODA solver improves performance significantly without failing any of our tests. Because we already modify `atol` based on the initial condition, this change mostly just prevents LSODA from trying to meet unreasonably tight error tolerances for those elements of the solution where the corresponding initial condition is zero. With this improvement we go from being sometimes more than 20x slower than the Fortran (for simple shear, excluding Numba compilation time) to being about 7 or 8 times slower.
=> Improve default LSODA tolerances

CHANGELOG.md, src/pydrex/core.py
This fixes a zero-division for some orientations under uniaxial compression, by catching the problematic values for slip invariants and returning null-values for orientation change and grain growth. There are some conditions where slip is simply not possible at all, and it is worth adding this check even though most Real World Problems are unlikely to hit this issue (strain rates would normally have pure shear, simple shear and compressional components combined).
=> Avoid zero-division under uniaxial compression

.github/workflows/ci.yml, .github/workflows/docs.yml, pyproject.toml, src/pydrex/io.py, src/pydrex/mesh.py, tests/test_doctests.py
In this PR, I removed maintenance for Python 3.10 and introduced testing for Python 3.13.
Additionally, I made the CI use the latest GitHub Windows runner, swapped the Arm64 version of macOS for the Intel one, and updated the versions of Actions used. 
Finally, I fixed errors and warnings raised when running the test suite with Python 3.13 and recent versions of Python packages.
=> Maintenance tasks related to system and software upgrades
